import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientComponent from "./components/clientComponent";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono", 
  weight: "100 900",
});
 

const valentrix = localFont({
  src : "./fonts/Valentrix.woff",
  variable : "--font-valentrix",
  weight : "100 900"
})



export const metadata: Metadata = {
  title: "Recipe",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${valentrix.variable} antialiased`}
      >
        <ClientComponent>
          {children}
        </ClientComponent>
      </body>
    </html>
  );
}
